### PR TITLE
Fixes e-mail sending when using Python 3.

### PR DESCRIPTION
**Pull request by href**
See #18.

I added pytest-localserver, which offers an actual smtp server to test against. I refrained from using it everywhere, because I don't understand all the test cases well enough. I think it would be a good idea though, testing against an actual server always beats testing against a mock.

See the test I added for an example.

Please let me know if there's anything unclear or if there are any things I should be doing differently.

### CODE REVIEW

**Comment by eugene-eeo** [comment]
Seems good to me, but the tests are failing- I'll merge them once we figure something out. Testing against a real server is something I wanted to do all along but didn't have the time to start. The test case looks good, but you may want to do some more integration tests, e.g. for other attachment objects. (Some day I would want to refactor the test suite but that's another topic altogether :sweat:)

**Comment by href** [comment]
Fixed the tests and added a new one that sends an attachment.

**Comment by eugene-eeo** [comment]
:+1: Thanks for the PR @href!

**Comment by href** [comment]
Welcome! Thanks for merging!

**Pull request merged**
